version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            apt-get update
            apt-get install awscli
            aws --version
      - run: tomcat:latest
